### PR TITLE
Simplify search-btn

### PR DESCRIPTION
**Pull request by gsolat**
## What does this PR do?
- Change search button for icon inside text field.
### Screenshot

screen shot 2016-09-28 at 3 50 01 pm
screen shot 2016-09-28 at 3 50 16 pm

### CODE REVIEW

**Review by milafrerichs — COMMENTED** [review]
not sure what the reason behind this is but it looks strange on my Chrome:
bildschirmfoto 2016-09-29 um 10 23 50

this is how it looks right now before your change:
bildschirmfoto 2016-09-29 um 10 24 51

**Comment by gsolat** [comment]
Hi Mila, this PR is for using the icon as a button to trigger the search. 

pr 52 remove-btn

**Comment by ingenieroariel** [comment]
@gsolat notice there is an extra search button in the screenshot that mila
shared.

**Comment by milafrerichs** [comment]
Yes and the new button is slightly bigger than the input field. Maybe 1-2 pixel.

**Comment by Lenninlasd** [comment]
I do not see any **extra** search button, the idea of this PR is remove the blue search button, for a visual enhancement

screen shot 2016-09-29 at 12 21 40

**Comment by milafrerichs** [comment]
ok, now the second button is gone for me as well but still have a small glitch:
the button appears to be bigger... I'm the only one seeing this? tested in Safari and Chrome in my Macbook Air.
bildschirmfoto 2016-09-30 um 13 51 08

**Comment by Lenninlasd** [comment]
Hi @milafrerichs we noticed this bug and we are fixing it in other PR

**Pull request merged**
